services:
  postgres:
    image: postgres:17.5
    container_name: tickethub-postgres
    environment:
      POSTGRES_DB: tickethub
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tickethub-network

  backend:
    build:
      context: ./backend
    container_name: tickethub-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tickethub
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/uploads
    networks:
      - tickethub-network

  client:
    build:
      context: ./client
      args:
        VITE_API_BASE_URL: http://tickethub-backend:8080
    container_name: tickethub-client
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - tickethub-network

volumes:
  pgdata:

networks:
  tickethub-network:
